version: '3'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  sms-gateway:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    restart: always
    expose:
      - 5000
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4000:4000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    environment:
      - TZ=Asia/Tehran
    depends_on:
      - sms-gateway